-- EBookMarket 초기 데이터
-- setup_books.py가 생성한 파일입니다.

INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('Pride and Prejudice', 'Jane Austen', 'A romantic novel that charts the emotional development of the protagonist Elizabeth Bennet.', 'covers/1342.jpg', 'epubs/1342.epub', 1000, 'NOVEL', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('Alice''s Adventures in Wonderland', 'Lewis Carroll', 'A young girl named Alice falls through a rabbit hole into a fantasy world.', 'covers/11.jpg', 'epubs/11.epub', 800, 'NOVEL', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('Frankenstein', 'Mary Shelley', 'A scientist creates a sapient creature in an unorthodox scientific experiment.', 'covers/84.jpg', 'epubs/84.epub', 1200, 'NOVEL', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 'Twelve stories featuring the brilliant detective Sherlock Holmes.', 'covers/1661.jpg', 'epubs/1661.epub', 1500, 'NOVEL', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('The Picture of Dorian Gray', 'Oscar Wilde', 'A philosophical novel about a handsome man whose portrait ages while he remains young.', 'covers/174.jpg', 'epubs/174.epub', 1000, 'NOVEL', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('A Tale of Two Cities', 'Charles Dickens', 'A historical novel set in London and Paris before and during the French Revolution.', 'covers/98.jpg', 'epubs/98.epub', 1300, 'HISTORY', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('Moby Dick', 'Herman Melville', 'The tale of the obsessive quest of Ahab for revenge on the whale Moby Dick.', 'covers/2701.jpg', 'epubs/2701.epub', 1200, 'NOVEL', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('A Modest Proposal', 'Jonathan Swift', 'A satirical essay suggesting that the poor Irish sell their children as food.', 'covers/1080.jpg', 'epubs/1080.epub', 500, 'ESSAY', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('Great Expectations', 'Charles Dickens', 'The story of the orphan Pip and his journey from humble beginnings to wealth.', 'covers/1400.jpg', 'epubs/1400.epub', 1100, 'NOVEL', NOW());
INSERT INTO books (title, author, description, cover_image_url, epub_url, original_price, category, created_at) VALUES ('Little Women', 'Louisa May Alcott', 'Follows the lives of the four March sisters as they grow from childhood to womanhood.', 'covers/514.jpg', 'epubs/514.epub', 900, 'NOVEL', NOW());